version: '3.8'
services:
  front:
    build: ./frontend/
    volumes:
      - ./frontend/app:/front
    ports:
      - 3050:3000
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true